github_provider:
    resource: ../src/Controller/GitHubController.php
    type:     annotation
    prefix: '/'
    name_prefix: 'auth_'

exception_controller:
    resource: ../src/Controller/GitHubController.php
    type:     annotation
    prefix: '/'
    name_prefix: 'auth_'

api_login_check:
    path: /api/login_check

controllers:
    resource: ../src/Controller/
    type: rest
    prefix: '/api/v1'

angular_github_callback:
    path: http://localhost:4200/callback